"""
DOCX Exporter for GDD AI
Converts generated markdown into a DOCX document.
"""

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
import re


def add_markdown_to_doc(doc: Document, markdown: str):
    """
    Lightweight markdown → DOCX converter.
    Supports:
        # Heading 1
        ## Heading 2
        ### Heading 3
        - Bullet points
        **bold**
        plain text
    """

    lines = markdown.split("\n")

    for line in lines:
        line = line.rstrip()

        # Heading 1
        if line.startswith("# "):
            p = doc.add_heading(line[2:], level=1)
            continue

        # Heading 2
        if line.startswith("## "):
            p = doc.add_heading(line[3:], level=2)
            continue

        # Heading 3
        if line.startswith("### "):
            p = doc.add_heading(line[4:], level=3)
            continue

        # Bullet list
        if line.startswith("- "):
            p = doc.add_paragraph(line[2:], style="List Bullet")
            continue

        # Empty line
        if line.strip() == "":
            doc.add_paragraph("")
            continue

        # Bold text formatting
        bold_matches = list(re.finditer(r"\*\*(.*?)\*\*", line))
        if bold_matches:
            p = doc.add_paragraph()
            last_index = 0

            for match in bold_matches:
                start, end = match.span()
                # Add normal text before the bold part
                if start > last_index:
                    p.add_run(line[last_index:start])

                # Add bold text
                bold_text = match.group(1)
                p.add_run(bold_text).bold = True

                last_index = end

            # Add remaining text
            if last_index < len(line):
                p.add_run(line[last_index:])

            continue

        # Normal paragraph
        doc.add_paragraph(line)


def export_to_docx(markdown: str, output_path: str) -> str:
    """
    Creates a DOCX file from markdown content.

    :param markdown: GDD markdown content
    :param output_path: Full path to save (e.g., '/tmp/gdd_output.docx')
    :return: output_path
    """
    doc = Document()

    # Title page
    title = doc.add_heading("Game Design Document", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph("Generated by Game Genie AI\n")

    doc.add_page_break()

    # Add parsed markdown
    add_markdown_to_doc(doc, markdown)

    # Save file
    doc.save(output_path)
    return output_path
